kind: PersistentVolume
apiVersion: v1
metadata:
  name: hello-logs-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/xxx/Documents/Docker/kube_schedule/logs"
